### ISSUE TITLE
Адрес страницы

### ISSUE THREAD

**Issue by vlleskov** [tarampampam/jquery.textmistake#1]
При нажатии Ctrl+Enter  не передается в форму адрес страницы http://clip2net.com/s/3hVCoTe
Скрипт установлен тут: http://vtambove.ru/news/society/109917/
В силу ограничений JQuery используется другой версии, сообщение обрабатывается, отправляется.

**Comment by tarampampam** [comment]
Да, действительно, ошибка имеет место быть. В репозитории её исправил, пожалуйста, обновите скрипт - теперь всё должно нормально работать.

Commit https://github.com/tarampampam/jquery.textmistake/commit/aa496cc460dcfd59a7984cc71f03c0b1ce29668a

**Comment by vlleskov** [comment]
Отлично! Тестим! 19.05.2015, 17:06, "kot" <notifications@github.com>:Да, действительно, ошибка имеет место быть. В репозитории её исправил, пожалуйста, обновите скрипт - теперь всё должно нормально работать.Commit aa496cc—Reply to this email directly or view it on GitHub.   -- С уважением, Владимир Лесковруководитель интернет отдела РГ ВДВ+7 (953) 704 28 18+7 (4752) 53 49 01Skype: tech_linehttp://vtambove.ruhttp://vdvtambov.ru

**Comment by vlleskov** [comment]
В результате эксплуатации выяснилось вот что.Очень не хватает в письме активной гиперссылки в урле. Приходится копировать - вставлять. 19.05.2015, 17:06, "kot" <notifications@github.com>:Да, действительно, ошибка имеет место быть. В репозитории её исправил, пожалуйста, обновите скрипт - теперь всё должно нормально работать.Commit aa496cc—Reply to this email directly or view it on GitHub.   -- С уважением, Владимир Лесковруководитель интернет отдела РГ ВДВ+7 (953) 704 28 18+7 (4752) 53 49 01Skype: tech_linehttp://vtambove.ruhttp://vdvtambov.ru

**Comment by tarampampam** [comment]
Попробуйте изменить строку **#319** с этой:
``
'<p><small>'+settings.l10n.urlHint+' '+url.text()+'</small></p>'+"\n\n"+
``
на эту:
``
'<p><small>'+settings.l10n.urlHint+' <a href="'+url.text()+'" target="_blank">'+url.text()+'</a></small></p>'+"\n\n"+
``
Или просто обновите скрипт из репозитория - соответствующий патч уже применен: https://github.com/tarampampam/jquery.textmistake/commit/679567747280048a795dde78fd7213d09885737f

**Comment by vlleskov** [comment]
Спасибо!!!! 20.05.2015, 11:57, "kot" <notifications@github.com>:Попробуйте изменить строку #319 с этой:  '<p><small>'+settings.l10n.urlHint+' '+url.text()+'</small></p>'+"\n\n"+  на эту:  '<p><small>'+settings.l10n.urlHint+' <a href="'+url.text()+'" target="_blank">'+url.text()+'</a></small></p>'+"\n\n"+  Или просто обновите скрипт из репозитория - соответствующий патч уже применен: 6795677—Reply to this email directly or view it on GitHub.   -- С уважением, Владимир Лесковруководитель интернет отдела РГ ВДВ+7 (953) 704 28 18+7 (4752) 53 49 01Skype: tech_linehttp://vtambove.ruhttp://vdvtambov.ru

**Comment by tarampampam** [comment]
Всё работает как нужно? Можем закрыть этот сабж?

**Comment by vlleskov** [comment]
Да, все хорошо! Спасибо огромное, редакция счастлива! 20.05.2015, 12:16, "kot" <notifications@github.com>:Всё работает как нужно? Можем закрыть этот сабж?—Reply to this email directly or view it on GitHub.   -- С уважением, Владимир Лесковруководитель интернет отдела РГ ВДВ+7 (953) 704 28 18+7 (4752) 53 49 01Skype: tech_linehttp://vtambove.ruhttp://vdvtambov.ru
