### ISSUE TITLE
Рекурсивное слияние заданных пользователем опций, и значений по-умолчанию

### ISSUE THREAD

**Issue by bashkos** [tarampampam/jquery.textmistake#2]
https://github.com/tarampampam/jquery.textmistake/blob/master/src/jquery.textmistake.js#L69

Наверное слияние должно быть рекурсивным (первый параметр `true` http://api.jquery.com/jquery.extend/), иначе неполная форма свойства `l10n` переписывает значение по-умолчанию, и все дочерние не упомянутые свойства просто пропадают, без возможности задействовать их значения по-умолчанию.

**Comment by tarampampam** [comment]
Да, действительно, больше спасибо за замечание - коррективы внес
