### ISSUE TITLE
Копия письма

### ISSUE THREAD

**Issue by vlleskov** [tarampampam/jquery.textmistake#3]
Было бы здорово реализовать функцию копии писем. 
К примеру хочется контролировать редакцию, а пересылку писем периодически либо отключают, либо она не работает по каким либо причинам.

**Comment by tarampampam** [comment]
Для этого достаточно в [331](https://github.com/tarampampam/jquery.textmistake/blob/master/src/jquery.textmistake.js#L331) строке изменить:
```javascript
// ...
'from_email': settings.mailFrom,
'to': [
  {'email': settings.mailTo, 'type': 'to'}  // <-- HERE
],
'autotext': 'true',
// ...
```
на:
```javascript
// ...
'from_email': settings.mailFrom,
'to': [
  {'email': settings.mailTo, 'type': 'to'},
  {'email': 'ANOTHER@EMAIL.COM', 'type': 'to'}  // <-- ADD THIS
],
'autotext': 'true',
// ...
```
Код не проверял "в живую", но сработать должно :)

**Comment by vlleskov** [comment]
Спасибо!!! 19.06.2015, 16:34, "kot" <notifications@github.com>:Для этого достаточно в 331 строке изменить:// ...
'from_email': settings.mailFrom,
'to': [
  {'email': settings.mailTo, 'type': 'to'}  // <-- HERE
],
'autotext': 'true',
// ...на:// ...
'from_email': settings.mailFrom,
'to': [
  {'email': settings.mailTo, 'type': 'to'},
  {'email': 'ANOTHER@EMAIL.COM', 'type': 'to'}  // <-- ADD THIS
],
'autotext': 'true',
// ...Код не проверял "в живую", но сработать должно :)—Reply to this email directly or view it on GitHub.   -- С уважением, Владимир Лесковруководитель интернет отдела РГ ВДВ+7 (953) 704 28 18+7 (4752) 53 49 01Skype: tech_linehttp://vtambove.ruhttp://vdvtambov.ru
