### ISSUE TITLE
i.imgur.com

### ISSUE THREAD

**Issue by siant91** [tarampampam/jquery.textmistake#4]
Здравствуйте!
Все изображения вашего скрипта находятся на i.imgur.com, который в данный момент недоступен. Где я могу скачать эти изображения?

**Comment by tarampampam** [comment]
Здравствуйте!

Только что проверил - все изображения доступны. Попробуйте использовать прокси для того что бы до них "достучаться", а после разместите их "у себя".

**Comment by siant91** [comment]
Точно, видимо i.imgur.com в Казахстане заблокировали. С помощью vpn скачал, спасибо!
