### ISSUE TITLE
Ограничения в Mandrill

### ISSUE THREAD

**Issue by aerohub** [tarampampam/jquery.textmistake#5]
Приветствую! В Mandrill теперь доступно бесплатно только первые 2000 сообщений, далее нужно переходить на платную основу. Есть ли возможность подключить другие подобные сервисы? 

UPD. Возможные альтернативы: 
- [SendPulse](https://sendpulse.com/ru/integrations/api#smtp) - 15 000 писем ежемесячно
- [Pepipost](http://www.pepipost.com/) - 25000 ежемесячно
- [Mailgun](https://www.mailgun.com/) - 10000 ежемесячно

**Comment by tarampampam** [comment]
Данный проект вообще есть смысл переписать с нуля, но на это пока что нет времени, к сожалению. Очень уж извините.

**Comment by aerohub** [comment]
Жаль, ибо Ваш скрипт - единственный из найденных не требует наличия php. Успехов!
